import { promises as fs } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(__dirname, "..");
const inFile = join(repoRoot, "lib", "data", "moduleSnippets.ts");
const outFile = join(repoRoot, "lib", "data", "moduleSnippetsTranslated.ts");

const TARGET_LANG = process.env.TARGET_LANG || "de";
const CONCURRENCY = Number(process.env.CONCURRENCY ?? 8);
const MAX_RETRIES = 3;

async function translateOne(text) {
  if (!text || !text.trim()) return text;
  const url =
    "https://translate.googleapis.com/translate_a/single?client=gtx&sl=en&tl=" +
    TARGET_LANG +
    "&dt=t&q=" +
    encodeURIComponent(text);
  for (let attempt = 0; attempt < MAX_RETRIES; attempt += 1) {
    try {
      const res = await fetch(url, {
        headers: {
          "User-Agent":
            "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36"
        }
      });
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const json = await res.json();
      return json[0].map((seg) => seg[0]).join("");
    } catch (e) {
      if (attempt === MAX_RETRIES - 1) {
        process.stderr.write(`! retry-failed: ${text.slice(0, 50)}\n`);
        return text;
      }
      await wait(300 + attempt * 400);
    }
  }
  return text;
}

function wait(ms) {
  return new Promise((r) => setTimeout(r, ms));
}

// Translate an array of strings with bounded concurrency.
async function translateAll(strings, onProgress) {
  const out = new Array(strings.length);
  let next = 0;
  let done = 0;
  await Promise.all(
    Array.from({ length: CONCURRENCY }).map(async () => {
      while (true) {
        const i = next;
        next += 1;
        if (i >= strings.length) return;
        out[i] = await translateOne(strings[i]);
        done += 1;
        if (done % 5 === 0 || done === strings.length) onProgress(done, strings.length);
      }
    })
  );
  return out;
}

function collectStrings(snippets) {
  const refs = []; // each: { set: (translated) => void, value: string }
  for (const moduleId of Object.keys(snippets)) {
    const snip = snippets[moduleId];
    refs.push({ value: snip.title, set: (v) => (snip.title = v) });
    for (const sec of snip.sections) {
      refs.push({ value: sec.heading, set: (v) => (sec.heading = v) });
      for (const block of sec.body) {
        if (block.kind === "paragraph") {
          refs.push({ value: block.text, set: (v) => (block.text = v) });
        } else if (block.kind === "list") {
          for (let i = 0; i < block.items.length; i += 1) {
            const idx = i;
            refs.push({ value: block.items[idx], set: (v) => (block.items[idx] = v) });
          }
        }
      }
    }
  }
  return refs;
}

async function main() {
  const src = await fs.readFile(inFile, "utf8");
  const start = src.indexOf("{", src.indexOf("moduleSnippets:"));
  if (start < 0) throw new Error("Could not locate moduleSnippets object");
  let depth = 0;
  let end = -1;
  for (let i = start; i < src.length; i += 1) {
    if (src[i] === "{") depth += 1;
    else if (src[i] === "}") {
      depth -= 1;
      if (depth === 0) {
        end = i + 1;
        break;
      }
    }
  }
  const snippets = JSON.parse(src.slice(start, end));

  const refs = collectStrings(snippets);
  process.stderr.write(`Translating ${refs.length} strings to ${TARGET_LANG} with concurrency=${CONCURRENCY}\n`);
  const startedAt = Date.now();
  const translated = await translateAll(
    refs.map((r) => r.value),
    (done, total) => {
      const elapsed = (Date.now() - startedAt) / 1000;
      const rate = done / Math.max(0.001, elapsed);
      const eta = ((total - done) / Math.max(0.001, rate)).toFixed(0);
      process.stderr.write(`\r${done}/${total} (${Math.round((done / total) * 100)}%) — ${rate.toFixed(1)}/s — ETA ${eta}s   `);
    }
  );
  process.stderr.write("\n");
  for (let i = 0; i < refs.length; i += 1) refs[i].set(translated[i]);

  // Merge with any existing translations file so multiple languages can coexist.
  let existing = {};
  try {
    const prev = await fs.readFile(outFile, "utf8");
    const m = prev.match(/= (\{[\s\S]*\}) as const;/);
    if (m) existing = JSON.parse(m[1]);
  } catch {
    /* fresh */
  }
  const merged = { ...existing, [TARGET_LANG]: snippets };

  const tsContent =
    "// Auto-generated by scripts/translate-modules.mjs.\n" +
    "// Run `TARGET_LANG=de node scripts/translate-modules.mjs` to refresh a language.\n\n" +
    "import type { ModuleSnippet } from \"@/lib/data/moduleSnippets\";\n\n" +
    "type Translations = Record<string, Record<string, ModuleSnippet>>;\n\n" +
    `export const moduleSnippetsTranslated: Translations = ${JSON.stringify(merged, null, 2)} as const;\n`;
  await fs.writeFile(outFile, tsContent, "utf8");
  process.stderr.write(`Wrote ${outFile}\n`);
}

main().catch((e) => {
  process.stderr.write(String(e?.stack ?? e) + "\n");
  process.exit(1);
});
